---
abstract: 'STF Client '
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-STF-Client
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Lite: 0
  Furl: 0
  HTTP::Status: 0
  MIME::Base64: 0
  Scalar::Util: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
